'use strict';//使用严格模式

//stateProvider对路由进行配置   urlRouterProvider对路径进行配置  
angular.module('app').config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$stateProvider
	.state('main',{
		url:'/main',
		templateUrl:'view/main.html',
		controller:'mainCtrl'
	})
	.state('shop',{
		url:'/shop',
		templateUrl:'view/shop.html',
		controller:'shopCtrl'
	})
	.state('login',{
		url:'/login',
		templateUrl:'view/login.html',
		controller:'loginCtrl'
	})
	.state('registered',{
		url:'/registered',
		templateUrl:'view/registered.html',
		controller:'registerCtrl'
	})
	.state('member_goTrace',{
		url:'/member_goTrace',
		templateUrl:'view/member_goTrace.html',
		controller:'memberCtrl'
	})
	.state('news',{
		url:'/news',
		templateUrl:'view/news.html',
		controller:'newsCtrl'
	})
	.state('about',{
		url:'/about',
		templateUrl:'view/about.html',
		controller:'aboutCtrl'
	})
	.state('shopList',{
		url:'/shopList',
		templateUrl:'view/shopList.html',
		controller:'shoplistCtrl'
	})
	.state('shopcart',{
		url:'/shopcart',
		templateUrl:'view/shopcart.html',
		controller:'shopcartCtrl'
	})
	.state('buy',{
		url:'/buy',
		templateUrl:'view/buy.html',
		controller:'buyCtrl'
	})
	;
	//当其他都没有匹配，默认跳到main
	$urlRouterProvider.otherwise('main');
}])